// This file is generated by Slice Machine. Update with care!

import Benefits from './Benefits';
import Conversion from './Conversion';
import Footer from './Footer';
import Header from './Header';
import Hero from './Hero';
import MobileApp from './MobileApp';
import Partners from './Partners';
import Stats from './Stats';
import Testimonials from './Testimonials';

export {
	Benefits,
	Conversion,
	Footer,
	Header,
	Hero,
	MobileApp,
	Partners,
	Stats,
	Testimonials,
};

export const components = {
	benefits: Benefits,
	conversion: Conversion,
	footer: Footer,
	header: Header,
	hero: Hero,
	mobile_app: MobileApp,
	partners: Partners,
	stats: Stats,
	testimonials: Testimonials,
};
